-mdoc: TOC with hyperlinks and PDF bookmarks
mdoc.7 taken from groff's groff_mdoc.7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,29 +1,18 @@
 #!/bin/sh
 
-# Copyright (c) 2016, Carsten Kunze
-# All rights reserved.
+# Copyright (c) 2016, Carsten Kunze <carsten.kunze@arcor.de>
 #
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
+# Permission to use, copy, modify, and/or distribute this software for any
+# purpose with or without fee is hereby granted, provided that the above
+# copyright notice and this permission notice appear in all copies.
 #
-# 1. Redistributions of source code must retain the above copyright notice,
-#    this list of conditions and the following disclaimer.
-#
-# 2. Redistributions in binary form must reproduce the above copyright notice,
-#    this list of conditions and the following disclaimer in the documentation
-#    and/or other materials provided with the distribution.
-#
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
-# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
-# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
-# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
-# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
-# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
-# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
-# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-# POSSIBILITY OF SUCH DAMAGE.
+# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
+# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
+# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
+# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
+# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
+# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
+# PERFORMANCE OF THIS SOFTWARE.
 
 usage () {
 	echo "Usage: $0 [-s]"
@@ -31,36 +20,11 @@ usage () {
 	exit $1
 }
 
-check_for () {
-	[ -e $LOG ] && echo >>$LOG
-	A="Checking for $1 ... "
-	echo "$A" >>$LOG
-	[ -z $SFLAG ] && printf "$A"
-}
-
-compile () {
-	rm -f $TMPNAM
-	$MAKE -f $OUTMK $TMPNAM >> $LOG 2>&1
-}
-
-test_result () {
-	if [ $? -eq 0 ]; then
-		echo success >>$LOG
-		[ -z $SFLAG ] && echo yes
-		[ -e $TMPC ] && rm -f $TMPC
-		true
-	else
-		[ -z $SFLAG ] && echo no
-		if [ -e $TMPC ]; then
-			echo "Failed program:" >>$LOG
-			pr -n -t $TMPC >>$LOG
-			rm -f $TMPC
-		fi
-		false
-	fi
-}
-
 SFLAG=
+MAKE=
+DEFS=
+LIB_LEX=
+LIB_CURSES=
 
 while [ $# -gt 0 ]; do
 	case $1 in
@@ -72,28 +36,68 @@ while [ $# -gt 0 ]; do
 	shift
 done
 
-INMK=mk.config
-OUTMK=cfg.mk
-CFG=config
-TMPNAM=.$CFG
-TMPMK=${TMPNAM}.mk
-TMPC=${TMPNAM}.c
-LOG=${CFG}.log
-rm -f $LOG
-cat version.mk $INMK > $OUTMK || exit 1
-DEFS=
-MAKE=
+check_for () {
+	[ -e $LOG ] && echo >>$LOG
+	A="Checking for $1 ... "
+	echo "$A" >>$LOG
+	[ -z "$SFLAG" ] && printf "$A"
+}
 
-check_for "make(1)"
+compile () {
+	rm -f ${TMPNAM}.o $TMPNAM $OUT $ERR
+	$MAKE -f $OUTMK $TMPNAM > $OUT 2> $ERR
+	RESULT=$?
+	cat $OUT $ERR >> $LOG
+	if [ $RESULT -eq 0 ]; then true; else false; fi
+}
 
-cat <<EOT >$TMPMK
+test_result () {
+	RESULT=$?
+	RESULT_TEXT=${1:-0} # 1: omit "no", 2: say nothing
+	if [ $RESULT -eq 0 ]; then
+		echo success >>$LOG
+		[ -z "$SFLAG" -a $RESULT_TEXT -lt 2 ] && \
+		    echo "yes$PASS_TEXT"
+		PASS_TEXT=
+		[ -e $TMPC ] && rm -f $TMPC
+		true
+	else
+		[ -z "$SFLAG" -a $RESULT_TEXT -lt 1 ] && echo no
+		if [ -e $TMPC ]; then
+			echo "Failed program:" >>$LOG
+			pr -n -t $TMPC >>$LOG
+			rm -f $TMPC
+		fi
+		false
+	fi
+}
+
+gen_mk () {
+	rm -f $OUTMK
+	[ -n "$LEX" ] && echo "LEX=$LEX" >> $OUTMK
+	[ -n "$FLOAT_STORE" ] && echo "FLOAT_STORE=$FLOAT_STORE" >> $OUTMK
+	[ -n "$DEFS" ] && echo "DEFINES=$DEFS" >> $OUTMK
+	[ -n "$INCDIR_CURSES" ] && echo "INCDIR_CURSES=$INCDIR_CURSES" >> $OUTMK
+	[ -n "$RPATH_CURSES" ] && echo "RPATH_CURSES=$RPATH_CURSES" >> $OUTMK
+	[ -n "$LIBDIR_CURSES" ] && echo "LIBDIR_CURSES=$LIBDIR_CURSES" \
+	    >> $OUTMK
+	[ -n "$LIB_CURSES" ] && echo "LIB_CURSES=$LIB_CURSES" >> $OUTMK
+	[ -n "$LIB_LEX" ] && echo "LIB_LEX=$LIB_LEX" >> $OUTMK
+	cat $INMK >> $OUTMK || exit 1
+}
+check_make () {
+	check_for "make(1)"
+
+	cat <<EOT >$TMPMK
 all:
 	true
 EOT
-make -f $TMPMK >> $LOG 2>&1
-test_result && MAKE=make
+	make -f $TMPMK >> $LOG 2>&1
+	test_result && {
+		MAKE=make
+		return
+	}
 
-if [ -z "$MAKE" ]; then
 	echo "Failed makefile:" >>$LOG
 	pr -n -t $TMPMK >>$LOG
 
@@ -105,74 +109,102 @@ all:
 EOT
 	bmake -f $TMPMK >> $LOG 2>&1
 	test_result && MAKE=bmake
-fi
+}
+check_lex () {
+	check_for '$(LEX)'
 
-check_for "strlcpy(3)"
-
-cat <<EOT >$TMPC
-	#include <string.h>
-	int
-	main (int argc, char **argv) {
-		char a[10];
-		strlcpy(a, *argv, sizeof a);
-		return 0;
-	}
+	cat <<EOT >$TMPL
+%%
+%%
+int main() { return 0; }
+int yywrap(void) { return 0; }
 EOT
-compile
-test_result && DEFS="$DEFS -DHAVE_STRLCPY"
+	compile
+	test_result && return
 
-check_for "strlcat(3)"
-
-cat <<EOT >$TMPC
-	#include <string.h>
-	int
-	main (int argc, char **argv) {
-		char a[10];
-		*a = 0;
-		strlcat(a, *argv, sizeof a);
-		return 0;
-	}
-EOT
-compile
-test_result && DEFS="$DEFS -DHAVE_STRLCAT"
-
-check_for "wcslcpy(3)"
-
-cat <<EOT >$TMPC
-	#include <stdio.h>
-	#include <wchar.h>
-	int
-	main (int argc, char **argv) {
-		wchar_t a, b;
-		a = getwchar();
-		wcslcpy(&b, &a, 1);
-		return 0;
-	}
-EOT
-compile
-test_result && DEFS="$DEFS -DHAVE_WCSLCPY"
-
-check_for '$(LEX)'
-
-cp pic/picl.l . || exit 1
-$MAKE -f $OUTMK picl.c >>$LOG 2>&1
-test_result
-
-if [ ! -e picl.c ]; then
 	check_for 'flex(1)'
 
-	$MAKE -f $OUTMK picl.c LEX=flex >>$LOG 2>&1
-	test_result && echo "LEX=flex" >>$OUTMK
-fi
+	LEX=flex
+	gen_mk
+	compile
+	test_result && return
 
-if [ ! -e picl.c ]; then
 	check_for 'lex(1)'
 
-	$MAKE -f $OUTMK picl.c LEX=lex >>$LOG 2>&1
-	test_result && echo "LEX=lex" >>$OUTMK
-fi
+	LEX=lex
+	gen_mk
+	compile
+	test_result && return
+}
+check_strlcpy () {
+	check_for "strlcpy(3)"
 
-rm -f picl.*
+	cat <<EOT >$TMPC
+#include <string.h>
+int
+main(int argc, char **argv) {
+	char a[10];
+	(void)argc;
+	strlcpy(a, *argv, sizeof a);
+	return 0;
+}
+EOT
+	compile
+	test_result && DEFS="$DEFS -DHAVE_STRLCPY"
+}
+check_strlcat () {
+	check_for "strlcat(3)"
 
-[ -n "$DEFS" ] && echo "DEFINES=$DEFS" >>$OUTMK
+	cat <<EOT >$TMPC
+#include <string.h>
+int
+main(int argc, char **argv) {
+	char a[10];
+	(void)argc;
+	*a = 0;
+	strlcat(a, *argv, sizeof a);
+	return 0;
+}
+EOT
+	compile
+	test_result && DEFS="$DEFS -DHAVE_STRLCAT"
+}
+check_wcslcpy () {
+	check_for "wcslcpy(3)"
+
+	cat <<EOT >$TMPC
+#include <stdio.h>
+#include <wchar.h>
+int
+main() {
+	wchar_t a, b;
+	a = getwchar();
+	wcslcpy(&b, &a, 1);
+	return 0;
+}
+EOT
+	compile
+	test_result && DEFS="$DEFS -DHAVE_WCSLCPY"
+}
+OUTMK=cfg.mk
+INMK=mk.config
+CFG=config
+TMPNAM=.$CFG
+TMPMK=${TMPNAM}.mk
+TMPC=${TMPNAM}.c
+TMPL=${TMPNAM}.l
+OUT=${TMPNAM}.out
+ERR=${TMPNAM}.err
+LOG=${CFG}.log
+rm -f $LOG
+gen_mk
+
+check_make
+check_lex
+check_strlcpy
+check_strlcat
+check_wcslcpy
+
+gen_mk
+cat version.mk >> $OUTMK || exit 1
 rm -f $TMPNAM*
